# MySQL config
#spring.application.name=English-Reading-Assistant
#
#server.port=8080
#
#spring.datasource.url=jdbc:mysql://localhost:3306/english-reading-assistant?serverTimezone=Asia/Shanghai
#
#spring.datasource.username=root
#
#spring.datasource.password=root
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# PostgreSQL config
spring.datasource.url=jdbc:postgresql://localhost:5432/english_reading_assistant

spring.datasource.username=postgres

spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver


# MyBatis
mybatis.configuration.map-underscore-to-camel-case=true

# Qwen API configuration
tongyi.api.key=

# fixed request URL
tongyi.api.url=https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation
# Using qwen-turbo
tongyi.model=qwen-turbo
# generation randomness
tongyi.temperature=0.3
# max output tokens
tongyi.max-token=2000

# RAG Chunk
rag.chunk.max-words=300
rag.chunk.overlap=50

# DashScope Embedding vector module configuration
dashscope.api-key=
dashscope.embedding-model=text-embedding-v4
tongyi.embedding-model=text-embedding-v4
tongyi.chat-model=qwen-turbo

# TEST
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl


#Redis server host address
spring.data.redis.host=localhost

#Redis service port
spring.data.redis.port=6379

#Redis database index
spring.data.redis.database=0

#Connection timeout,unit: millisecond,5s = 5000ms
spring.data.redis.timeout=5000