spring.application.name=English-Reading-Assistant

server.port=8080


spring.datasource.url=jdbc:mysql://localhost:3306/english-reading-assistant?serverTimezone=Asia/Shanghai

spring.datasource.username=root

spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# MyBatis
mybatis.configuration.map-underscore-to-camel-case=true