#### 上传txt文件
POST http://localhost:8080/sentence/analyze
Content-Type: application/json

{
  "userId": 1,
  "bookId": 1,
  "chapterId": 1,
  "sentence": "I didn't realize how difficult it would be."
}